blank_issues_enabled: false
contact_links:
  - name: Slimefun Legacy issues
    url: https://github.com/wickidcow/Slimefun-Legacy/issues
    about: Report problems that affect Slimefun Legacy itself rather than Networks.
